version: 2

updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
      time: "17:00"
    ignore:
      - dependency-name: "io.papermc.paper:paper-api"
        versions: [ "*" ]