[versions]
shadow = "8.3.6"
invUI = "1.45"
commandAPI = "10.0.1"
configLib = "4.6.1"
lombok = "1.18.36"
paper = "1.21.4-R0.1-SNAPSHOT"

[libraries]
invUI = { group = "xyz.xenondevs.invui", name = "invui", version.ref = "invUI" }
commandAPI = { group = "dev.jorel", name = "commandapi-bukkit-shade", version.ref = "commandAPI" }
configLib = { group = "de.exlll", name = "configlib-paper", version.ref = "configLib" }
lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok" }
paper = { group = "io.papermc.paper", name = "paper-api", version.ref = "paper" }

[bundles]

[plugins]
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }